### ISSUE TITLE
👑 Release v9.34

### ISSUE THREAD

**Issue by Tirokk** [New-Soul-Of-Science-Project/New-Soul-Of-Science-Project-Web#16]
## 👑 EPIC

Release v9.34

### Todo

- [ ] #5 
- [ ] #10

##### Link to

- [ ] https://nsosp.org/download/Yunite-Impulsvortrag-20230920-1700/Eine-positive-Vision-fuer-unsere-Zukunft-Impulsvortrag-Spannungsspiel-des-Lebens-20230920-3-mit-Links.pdf

##### Mobility

- [ ] for mobility we have the following issues:
  - [ ] size of some sub texts under figures etc.
  - [x] hyphenation of all theme home content lists

<img width="300" alt="IMG_8452" src="https://github.com/New-Soul-Of-Science-Project/New-Soul-Of-Science-Project-Web/assets/25344101/9c22af27-1f88-45e0-b4aa-5aaab8637f25">

<img width="300" alt="IMG_8454" src="https://github.com/New-Soul-Of-Science-Project/New-Soul-Of-Science-Project-Web/assets/25344101/1231d4ba-3451-4a77-a0b5-1e20835b2180">

##### Content

- [x] Biordinal Numbers – page `Einleitung`:
  - [x] refine to implement that the `Primzahl-Produktvermutung` is proofed:

<img width="300" alt="IMG_8828" src="https://github.com/New-Soul-Of-Science-Project/New-Soul-Of-Science-Project-Web/assets/25344101/7e4824e1-f79d-43e5-802f-d888d676ad08">

**Comment by Tirokk** [comment]
Partly solved by #17 
Lets close it and open a next release
