### ISSUE TITLE
👑 Release v9.35

### ISSUE THREAD

**Issue by Tirokk** [New-Soul-Of-Science-Project/New-Soul-Of-Science-Project-Web#18]
## 👑 EPIC

Release v9.35

### Todo

- [ ] #5 
- [ ] #10

##### Link to

- [ ] Eine Positive Vision Für Unsere Zukunft: https://nsosp.org/download/Yunite-Impulsvortrag-20230920-1700/Eine-positive-Vision-fuer-unsere-Zukunft-Impulsvortrag-Spannungsspiel-des-Lebens-20230920-3-mit-Links.pdf

##### Content

- [ ] none

##### Mobility

- [ ] for mobility we have the following issues:
  - [ ] size of some sub texts under figures etc.

<img width="300" alt="IMG_8452" src="https://github.com/New-Soul-Of-Science-Project/New-Soul-Of-Science-Project-Web/assets/25344101/9c22af27-1f88-45e0-b4aa-5aaab8637f25">
