### ISSUE TITLE
👑 Release v9.36

### ISSUE THREAD

**Issue by Tirokk** [New-Soul-Of-Science-Project/New-Soul-Of-Science-Project-Web#21]
## 👑 EPIC

Release v9.36

### Todo

- [ ] #5 
- [ ] #10

##### Link to

- [ ] Eine Positive Vision Für Unsere Zukunft: https://nsosp.org/download/Yunite-Impulsvortrag-20230920-1700/Eine-positive-Vision-fuer-unsere-Zukunft-Impulsvortrag-Spannungsspiel-des-Lebens-20230920-3-mit-Links.pdf

##### Content

- [x] image has to much width

<img width="1644" alt="Bildschirmfoto 2024-02-28 um 16 11 52" src="https://github.com/New-Soul-Of-Science-Project/New-Soul-Of-Science-Project-Web/assets/25344101/ed680112-55f2-4ece-b7d7-34516fd9ece0">

##### Mobility

- [ ] for mobility we have the following issues:
  - [ ] size of some sub texts under figures etc.

<img width="300" alt="IMG_8452" src="https://github.com/New-Soul-Of-Science-Project/New-Soul-Of-Science-Project-Web/assets/25344101/9c22af27-1f88-45e0-b4aa-5aaab8637f25">
