### ISSUE TITLE
🚀 Add `Operial Theory`, `Biordinal Numbers`, and `New Soul Of Science Academy` to Readme

### ISSUE THREAD

**Issue by Tirokk** [New-Soul-Of-Science-Project/New-Soul-Of-Science-Project-Web#3]
## 🚀 Change

Add Operialtheorie to Readme.

### Todo

- [x] create a logo for the Operial Theory
- [x] create a logo for the Biordinal Numbers
- [x] create a logo for the New Soul Of Science Academy
- [x] add all three to the page header and create favicon
- [x] add all three to the readme

**Comment by Tirokk** [comment]
solved
